### ISSUE TITLE
JamfUploaderTeamsNotifier - MS announces retirement of Teams connectors

### ISSUE THREAD

**Issue by jshirle2** [grahampugh/jamf-upload#165]
Hello, 

This is more of a question than a specific issue, but per the blog post here: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams it seems that JamfUploaderTeamsNotifier will need to be changed. I was just wondering if this is in the works, etc. 

Thanks!

**Comment by grahampugh** [comment]
I don't have any access to Teams anymore, but if this change is anything like what Slack did, it wouldn't affect the processor. It would just change how you go about creating the "Incoming Webhook" in Teams, i.e. how you generate the webhook URL.

However, I'll ping @jc0b who created this processor.

**Comment by jc0b** [comment]
I also don't have access to Teams anymore 😅 but yeah, as long as they haven't changed the card format it should still work.

**Comment by jc0b** [comment]
Yup, at a glance it appears that the webhook format still matches [what you need to send Teams](https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1%2Cdotnet#microsoft-teams-webhook) (although it's possible I need to switch it to an AdaptiveCard). I'll take a little look at this when I have some time.

**Comment by jshirle2** [comment]
I can test it when I get a chance in its current form. I also am available to assist with testing as I heavily use Teams in my current role.

**Comment by jc0b** [comment]
I have [a copy of the processor](https://github.com/jc0b/jamf-upload/blob/main/JamfUploaderProcessors/JamfUploaderTeamsNotifier.py) in a fork that has been updated to use AdaptiveCard instead of MessageCard, using https://adaptivecards.io/designer/.

Two things:
- I have no idea if this works at all
- I have no idea if this breaks functionality for those using the old integration (although I don't believe it would)

Please test and let me know :)

**Comment by randomName0815** [comment]
I tested it via powerautomate webhook template on a teams channel and found some small things.
https://github.com/jc0b/jamf-upload/pull/1
unfortunately, i cannot test the creation of the workflow in teams due to internal guidelines.
but it would probably be good to keep it backwards compatible so that everyone can switch over as soon as they are ready

**Comment by randomName0815** [comment]
just tested with an old teams connector, it dont breaks it ! ... didn't expect that this would work  😅

**Comment by jc0b** [comment]
Yup, looks like in [the docs](https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1%2Cdotnet#post-adaptive-card-in-a-chat-or-channel) 1.2 is the AdaptiveCard version they use. Thanks for the fix, I'll merge your changes into my fork. @grahampugh would you like more feedback on this before I open a PR?
